### ISSUE TITLE
Refactor API Endpoints for Improved Data Flow and Usability

### ISSUE THREAD

**Issue by LouisPauchet** [LouisPauchet/UNIS_SvalbardWeatherInformation#16]
### **Description**
The current API design requires enhancements to handle fixed and mobile stations effectively while ensuring metadata consistency, including the station's position and available variables. This issue outlines a plan to redesign the API for improved usability, scalability, and clarity.

---

### **Proposed Changes**

1. **Online Stations Endpoint**  
   Introduce an endpoint to retrieve a list of online stations, filtered by type:
   - **Endpoint**: `/api/station-data/online?type=<type>`
   - **Query Parameter**:  
     - `type`: Specifies station type (`fixed`, `mobile`, or `all`).
   - **Expected Response**:  
     ```json
     {
         "online_stations": [
             { "id": "station_1", "name": "Station 1", "type": "fixed", "location": { "lat": 78.223, "lon": 15.646 } },
             { "id": "station_2", "name": "Station 2", "type": "mobile", "location": { "lat": 78.234, "lon": 15.678 } }
         ]
     }
     ```

2. **Unified Station Metadata Endpoint**  
   A single endpoint for querying station metadata by ID:
   - **Endpoint**: `/api/station-data/<station_id>`
   - **Behavior**:
     - Returns metadata and general information about the station, including position and available variables.
     - Automatically identifies the type of station (fixed or mobile).
   - **Expected Response**:
     - **For Fixed Stations**:
       ```json
       {
           "id": "station_1",
           "name": "Fixed Station 1",
           "type": "fixed",
           "location": { "lat": 78.223, "lon": 15.646 },
           "variables": ["temperature", "humidity", "wind_speed"],
           "status": "online",
           "last_updated": "2024-11-18T10:00:00Z"
       }
       ```
     - **For Mobile Stations**:
       ```json
       {
           "id": "station_2",
           "name": "Mobile Station 2",
           "type": "mobile",
           "location": { "lat": 78.223, "lon": 15.646 },
           "variables": ["temperature", "humidity", "speed"],
           "status": "online",
           "last_updated": "2024-11-18T10:00:00Z"
       }
       ```

3. **Real-Time Data Endpoint for Map Display**  
   Retrieve the latest data for a station, including positional data for mobile stations:
   - **Endpoint**: `/api/station-data/<station_id>?data=now`
   - **Expected Response**:
     - **For Fixed Stations**:
       ```json
       {
           "id": "station_1",
           "timeseries": [
               { "timestamp": "2024-11-18T10:00:00Z", "temperature": 22.5, "humidity": 65, "wind_speed": 10.2 }
           ]
       }
       ```
     - **For Mobile Stations**:
       ```json
       {
           "id": "station_2",
           "timeseries": [
               {
                   "timestamp": "2024-11-18T10:00:00Z",
                   "position": { "lat": 78.223, "lon": 15.646 },
                   "temperature": 22.5,
                   "humidity": 65,
                   "speed": 5.0
               }
           ]
       }
       ```

4. **Time-Series Data Endpoint**  
   Add an endpoint to retrieve historical data for a station, including positional data for mobile stations:
   - **Endpoint**: `/api/station-data/<station_id>?data=timeseries&start=YYYY-MM-DDhhmm&end=YYYY-MM-DDhhmm`
   - **Query Parameters**:  
     - `start`: Start timestamp for the time range.
     - `end`: End timestamp for the time range.
   - **Expected Response**:
     - **For Fixed Stations**:
       ```json
       {
           "id": "station_1",
           "timeseries": [
               { "timestamp": "2024-11-18T08:00:00Z", "temperature": 22.0, "humidity": 63 },
               { "timestamp": "2024-11-18T09:00:00Z", "temperature": 22.3, "humidity": 64 }
           ]
       }
       ```
     - **For Mobile Stations**:
       ```json
       {
           "id": "station_2",
           "timeseries": [
               {
                   "timestamp": "2024-11-18T08:00:00Z",
                   "position": { "lat": 78.223, "lon": 15.646 },
                   "temperature": 22.0,
                   "humidity": 63,
                   "speed": 5.0
               },
               {
                   "timestamp": "2024-11-18T09:00:00Z",
                   "position": { "lat": 78.224, "lon": 15.647 },
                   "temperature": 22.3,
                   "humidity": 64,
                   "speed": 5.2
               }
           ]
       }
       ```

---

### **Tasks**

- [ ] Create an endpoint to list online stations: `/api/station-data/online?type=`.
- [ ] Refactor the API to use a unified endpoint for querying station metadata: `/api/station-data/<station_id>`.
  - [ ] Ensure the response includes the position for all station types.
  - [ ] Include available variables in the metadata response.
- [ ] Add a new endpoint to retrieve real-time data for map display: `/api/station-data/<station_id>?data=now`.
  - [ ] Ensure positional data is included for mobile stations.
- [ ] Introduce an endpoint to retrieve time-series data for a station: `/api/station-data/<station_id>?data=timeseries&start=YYYY-MM-DD&end=YYYY-MM-DD`.
  - [ ] Include positional data for mobile stations in the response.
- [ ] Standardize error handling across all endpoints with appropriate status codes (`400`, `404`, `500`).

---

### **Acceptance Criteria**

- The API supports all proposed endpoints with the described behavior.
- Positional data is always included in the metadata response for all stations.
- Positional data is included in time-series and real-time responses for mobile stations.
- Available variables are included in the metadata response for all stations.
- The response format for fixed and mobile stations is consistent where applicable.
- Endpoints are tested for performance and scalability.
- Comprehensive documentation is added for all endpoints.
